services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lorica-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
    - .:/lorica-api
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  postgres:
    image: postgres:17.6
    container_name: lorica-postgres
    environment:
      POSTGRES_DB: lorica_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: