services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lorica-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: always
  postgres:
    image: postgres:17.6
    container_name: lorica-postgres
    environment:
      POSTGRES_DB: lorica_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: