services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lorica-api
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
    - .:/lorica-api
    restart: unless-stopped
    command:  >
      sh -c "
        python -m app.core.db.init_db &&
        python -m app.core.db.seed &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "
  postgres:
    image: postgres:17.6
    container_name: lorica-postgres
    environment:
      POSTGRES_DB: lorica_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lorica_dev"]
      interval: 2s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: